name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: :VamshiApp"
      DEPLOY_ENV: "dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip to latest
        run: python -m pip install --upgrade pip

      - name: Install a Python package (numpy)
        run: pip install numpy

      - name: Run simple Python command
        run: python -c "print('CI pipeline is working! From Vamshi')"
      - name: Print secret (masked)
        run: echo "The Secret is $MY_SECRET"
        env: 
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - name: Print environment variables
          run: |
              echo 'App name is: $APP_NAME"
              echo "Deploying to environment: $DEPLOY_ENV"
          
